---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cluster-guide-tls
spec:
  commonName: cluster.guide
  secretName: cluster-guide-tls
  dnsNames:
    - cluster.guide
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
